# Generated by Django 4.2.21 on 2025-05-23 07:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Access',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dashboard_full_access', models.BooleanField(default=False)),
                ('dashboard_view', models.BooleanField(default=False)),
                ('dashboard_create', models.BooleanField(default=False)),
                ('dashboard_edit', models.BooleanField(default=False)),
                ('dashboard_delete', models.BooleanField(default=False)),
                ('task_full_access', models.BooleanField(default=False)),
                ('task_view', models.BooleanField(default=False)),
                ('task_create', models.BooleanField(default=False)),
                ('task_edit', models.BooleanField(default=False)),
                ('task_delete', models.BooleanField(default=False)),
                ('project_tracker_full_access', models.BooleanField(default=False)),
                ('project_tracker_view', models.BooleanField(default=False)),
                ('project_tracker_create', models.BooleanField(default=False)),
                ('project_tracker_edit', models.BooleanField(default=False)),
                ('project_tracker_delete', models.BooleanField(default=False)),
                ('onboarding_full_access', models.BooleanField(default=False)),
                ('onboarding_view', models.BooleanField(default=False)),
                ('onboarding_create', models.BooleanField(default=False)),
                ('onboarding_edit', models.BooleanField(default=False)),
                ('onboarding_delete', models.BooleanField(default=False)),
                ('attendance_full_access', models.BooleanField(default=False)),
                ('attendance_view', models.BooleanField(default=False)),
                ('attendance_create', models.BooleanField(default=False)),
                ('attendance_edit', models.BooleanField(default=False)),
                ('attendance_delete', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RenameField(
            model_name='role',
            old_name='name',
            new_name='role',
        ),
        migrations.AlterUniqueTogether(
            name='role',
            unique_together={('role', 'department')},
        ),
        migrations.AddField(
            model_name='role',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Permission',
        ),
        migrations.AddField(
            model_name='access',
            name='role',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='access', to='erp.role'),
        ),
    ]
