# Generated by Django 4.2.21 on 2025-06-06 09:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0003_category_color_size_supplier_taxcode_uom_warehouse_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesRep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_id', models.CharField(editable=False, max_length=10, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('customer_type', models.CharField(choices=[('Individual', 'Individual'), ('Business', 'Business'), ('Organization', 'Organization')], max_length=20)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=10)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_number', models.CharField(max_length=15)),
                ('address', models.TextField(blank=True, null=True)),
                ('street', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('zip_code', models.CharField(max_length=10)),
                ('country', models.CharField(max_length=100)),
                ('company_name', models.CharField(blank=True, max_length=100, null=True)),
                ('industry', models.CharField(blank=True, choices=[('Technology', 'Technology'), ('Manufacturing', 'Manufacturing'), ('Healthcare', 'Healthcare'), ('Finance', 'Finance'), ('Education', 'Education'), ('Construction', 'Construction'), ('Transportation', 'Transportation'), ('Hospitality', 'Hospitality'), ('Energy', 'Energy'), ('Media & Comms', 'Media & Comms')], max_length=50, null=True)),
                ('custom_industry', models.CharField(blank=True, max_length=50, null=True)),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('gst_tax_id', models.CharField(blank=True, max_length=50, null=True)),
                ('credit_limit', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('available_limit', models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=10, null=True)),
                ('billing_address', models.TextField(blank=True, null=True)),
                ('shipping_address', models.TextField(blank=True, null=True)),
                ('payment_terms', models.CharField(blank=True, choices=[('Net 15', 'Net 15'), ('Net 30', 'Net 30'), ('Net 45', 'Net 45'), ('Net 60', 'Net 60'), ('Due on Receipt', 'Due on Receipt')], max_length=50, null=True)),
                ('custom_payment_terms', models.CharField(blank=True, max_length=50, null=True)),
                ('credit_term', models.CharField(blank=True, choices=[('Standard', 'Standard'), ('Extended', 'Extended'), ('Advance', 'Advance'), ('Prepaid', 'Prepaid'), ('COD (Cash on Delivery)', 'COD (Cash on Delivery)')], max_length=50, null=True)),
                ('custom_credit_term', models.CharField(blank=True, max_length=50, null=True)),
                ('last_edited', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(default='Admin', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_sales_rep', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='erp.salesrep')),
            ],
        ),
    ]
